LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY ARITHMETIC_RIGHT_SHIFTER IS
    GENERIC (
        DATA_WIDTH   : INTEGER := 32;
        SHIFT_AMOUNT : INTEGER := 6
    );
    PORT (
        D_IN  : IN  STD_LOGIC_VECTOR;
        D_OUT : OUT STD_LOGIC_VECTOR
    );
END ARITHMETIC_RIGHT_SHIFTER;

ARCHITECTURE BEHAVIORAL OF ARITHMETIC_RIGHT_SHIFTER IS
BEGIN
    D_OUT <= (SHIFT_AMOUNT - 1 DOWNTO 0 => D_IN(DATA_WIDTH - 1)) & D_IN(DATA_WIDTH - 1 DOWNTO SHIFT_AMOUNT);

END ARCHITECTURE BEHAVIORAL;