LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY COMPARATOR IS
    GENERIC (DATA_WIDTH : INTEGER := 16);
    PORT (
        A  : IN  STD_LOGIC_VECTOR;
        B  : IN  STD_LOGIC_VECTOR;
        GT : OUT STD_LOGIC;
        EQ : OUT STD_LOGIC;
        LT : OUT STD_LOGIC
    );
END ENTITY COMPARATOR;

ARCHITECTURE EXPRESSION OF COMPARATOR IS
BEGIN
    EQ <= '1' WHEN SIGNED(A) = SIGNED(B) ELSE '0';
    GT <= '1' WHEN SIGNED(A) > SIGNED(B) ELSE '0';
    LT <= '1' WHEN SIGNED(A) < SIGNED(B) ELSE '0';
END ARCHITECTURE EXPRESSION;
