LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

PACKAGE MATRIX_PKG IS
    CONSTANT DATA_WIDTH : INTEGER := 32;
    SUBTYPE DATA_WORD IS STD_LOGIC_VECTOR(DATA_WIDTH - 1 DOWNTO 0);
    TYPE MATRIX IS ARRAY (NATURAL RANGE <>) OF DATA_WORD;
END PACKAGE MATRIX_PKG;