LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY RELU_ACTIVATION IS
    GENERIC (BIT_WIDTH : INTEGER := 21);
    PORT (X  : IN  STD_LOGIC_VECTOR(BIT_WIDTH - 1 DOWNTO 0);
          F_X : OUT STD_LOGIC_VECTOR(BIT_WIDTH - 1 DOWNTO 0));
END RELU_ACTIVATION;

ARCHITECTURE ARCH_RELU OF RELU_ACTIVATION IS
BEGIN    
    F_X <= (OTHERS => '0') WHEN X(BIT_WIDTH - 1) = '1' ELSE X;
END ARCH_RELU;

