LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE work.MATH_PKG.ALL;

ENTITY ADDER_TREE IS
    GENERIC (
        NUM_INPUTS : INTEGER := 9;
        DATA_WIDTH : INTEGER := 8;
        SUM_WIDTH  : INTEGER := 8
    );
    PORT (
        DATA_IN  : IN  STD_LOGIC_VECTOR((NUM_INPUTS * DATA_WIDTH) - 1 DOWNTO 0);
        DATA_OUT : OUT STD_LOGIC_VECTOR(SUM_WIDTH - 1 DOWNTO 0)
    );
END ENTITY ADDER_TREE;

ARCHITECTURE RTL OF ADDER_TREE IS

    COMPONENT ADDITION IS
    GENERIC (N : INTEGER := 16 );
    PORT (
            X   : IN  STD_LOGIC_VECTOR(N-1 DOWNTO 0);
            Y   : IN  STD_LOGIC_VECTOR(N-1 DOWNTO 0);
            ADD : OUT STD_LOGIC_VECTOR(N-1 DOWNTO 0)
        );
    END COMPONENT;

    CONSTANT LEVELS  : INTEGER := LOG2(NUM_INPUTS);
    CONSTANT P_NODES   : INTEGER := 2**LEVELS;  
    CONSTANT EXT_WIDTH : INTEGER := DATA_WIDTH + LEVELS;

    SIGNAL INPUT_SUM : STD_LOGIC_VECTOR(((LEVELS + 1) * P_NODES * EXT_WIDTH) - 1 DOWNTO 0) := (OTHERS => '0');

BEGIN
--LEVEL 0
    INPUT_GEN: FOR I IN 0 TO NUM_INPUTS - 1 GENERATE
        INPUT_SUM(((I + 1) * EXT_WIDTH) - 1 DOWNTO (I * EXT_WIDTH)) <= STD_LOGIC_VECTOR(RESIZE(SIGNED(DATA_IN(((I + 1) * DATA_WIDTH) - 1 DOWNTO (I * DATA_WIDTH))), EXT_WIDTH));
    END GENERATE INPUT_GEN;

    ODD_CHECK: FOR I IN NUM_INPUTS TO P_NODES - 1 GENERATE
    INPUT_SUM(((I + 1) * EXT_WIDTH) - 1 DOWNTO (I * EXT_WIDTH)) <= (OTHERS => '0');
    END GENERATE ODD_CHECK;

    LEVEL_GEN: FOR L IN 1 TO LEVELS GENERATE
        ADDER_GEN: FOR A IN 0 TO (P_NODES / (2**L)) - 1 GENERATE
            U_ADDER: ADDITION
            GENERIC MAP (
                N => EXT_WIDTH 
            )
            PORT MAP (
                X   => INPUT_SUM(((((L - 1) * P_NODES) + (2 * A) + 1) * EXT_WIDTH) - 1 DOWNTO ((((L - 1) * P_NODES) + (2 * A)) * EXT_WIDTH)),     
                Y   => INPUT_SUM(((((L - 1) * P_NODES) + (2 * A + 1) + 1) * EXT_WIDTH) - 1 DOWNTO ((((L - 1) * P_NODES) + (2 * A + 1)) * EXT_WIDTH)), 
                ADD => INPUT_SUM((((L * P_NODES) + A + 1) * EXT_WIDTH) - 1 DOWNTO (((L * P_NODES) + A) * EXT_WIDTH))              
            );
        END GENERATE ADDER_GEN;
    END GENERATE LEVEL_GEN;

    DATA_OUT <= STD_LOGIC_VECTOR(RESIZE(SIGNED(INPUT_SUM((((LEVELS * P_NODES) + 1) * EXT_WIDTH) - 1 DOWNTO ((LEVELS * P_NODES) * EXT_WIDTH))), SUM_WIDTH));

END ARCHITECTURE RTL;
