LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY ADDITION IS
    GENERIC (N : INTEGER := 8 );
    PORT (
        X   : IN  STD_LOGIC_VECTOR(N - 1 DOWNTO 0);
        Y   : IN  STD_LOGIC_VECTOR(N - 1 DOWNTO 0);
        ADD : OUT STD_LOGIC_VECTOR(N - 1 DOWNTO 0)
    );
END ENTITY ADDITION;

ARCHITECTURE BEHAVIORAL OF ADDITION IS
BEGIN
    ADD <= STD_LOGIC_VECTOR(SIGNED(X) + SIGNED(Y));
END ARCHITECTURE BEHAVIORAL;