LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.TESTPACK.ALL;

ENTITY ARRAY_MULTIPLIER_TB IS END ARRAY_MULTIPLIER_TB;
ARCHITECTURE BEHAVIOR OF ARRAY_MULTIPLIER_TB IS
    CONSTANT N_TB : POSITIVE := 4;
    SIGNAL X, Y   : STD_LOGIC_VECTOR(N_TB-1 DOWNTO 0) := (OTHERS => '0');
    SIGNAL Z   : STD_LOGIC_VECTOR((2*N_TB)-1 DOWNTO 0);
BEGIN
    UUT1: CONFIGURATION WORK.CONFIG_ARRAY_MULTIPLIER
        PORT MAP (X => X,Y => Y,Z => Z);
        
     SET_X_Y_AND_CHECK:PROCESS
        VARIABLE SEED1, SEED2      : POSITIVE := 1;
        VARIABLE EXPECTED_Z : UNSIGNED((2*N_TB)-1 DOWNTO 0);
    BEGIN
     FOR I IN 0 TO 19 LOOP
        WAIT FOR 10 NS;
        RANDOM(SEED1, SEED2, X);
        RANDOM(SEED1, SEED2, Y);
        WAIT FOR 10 NS;
        EXPECTED_Z := UNSIGNED(X) * UNSIGNED(Y);    
            ASSERT (UNSIGNED(Z) = EXPECTED_Z)
                REPORT "MISMATCH DETECTED! X: " & INTEGER'IMAGE(TO_INTEGER(UNSIGNED(X))) & 
                       ", Y: " & INTEGER'IMAGE(TO_INTEGER(UNSIGNED(Y))) &
                       ", EXPECTED Z: " & INTEGER'IMAGE(TO_INTEGER(EXPECTED_Z)) &
                       ", ACTUAL Z: " & INTEGER'IMAGE(TO_INTEGER(UNSIGNED(Z)))
                SEVERITY ERROR;

            WAIT FOR 10 NS;
        END LOOP;
            
        REPORT "SIMULATION COMPLETED SUCCESSFULLY." 
        SEVERITY NOTE;
        WAIT;   
    END PROCESS SET_X_Y_AND_CHECK;
END ARCHITECTURE BEHAVIOR;