LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY BIT_MULTIPLIER IS
    PORT (XI, YI, PI, CI   : IN  STD_LOGIC;
          XO, YO, PO, CO : OUT STD_LOGIC);
END ENTITY BIT_MULTIPLIER;

ARCHITECTURE LOGICAL OF BIT_MULTIPLIER IS
    SIGNAL XY : STD_LOGIC;
BEGIN
    XY <= XI AND YI;
    CO <= (XY AND PI) OR (XY AND CI) OR (PI AND CI);
    PO <= XY XOR PI XOR CI;
    XO <= XI;
    YO <= YI;   
END ARCHITECTURE LOGICAL;
