LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE IEEE.MATH_REAL.ALL;
USE WORK.MATH_PKG.ALL;

ENTITY MATRIX_MULTIPLIER IS
    GENERIC (
        ROW_A             : INTEGER := 2;
        COLUMN_B          : INTEGER := 2;
        COMMON            : INTEGER := 2;
        SIZE_EACH_PRODUCT : INTEGER := 8 
    );
    PORT (
        A              : IN  STD_LOGIC_VECTOR(ROW_A * COMMON*SIZE_EACH_PRODUCT - 1 DOWNTO 0);
        B              : IN  STD_LOGIC_VECTOR(COMMON * COLUMN_B*SIZE_EACH_PRODUCT - 1 DOWNTO 0);
        OUT_MULTIPLIER : OUT STD_LOGIC_VECTOR(ROW_A * COLUMN_B * SUM_WIDTH((SIZE_EACH_PRODUCT * 2), COMMON) - 1 DOWNTO 0)
    );
END ENTITY MATRIX_MULTIPLIER;

ARCHITECTURE STRUCTURAL OF MATRIX_MULTIPLIER IS

    COMPONENT SIGNED_MULTIPLIER_WRAPPER IS
        GENERIC (N : INTEGER := 8 );
        PORT (
            X_SIGNED : IN  STD_LOGIC_VECTOR(N - 1 DOWNTO 0);
            Y_SIGNED : IN  STD_LOGIC_VECTOR(N - 1 DOWNTO 0);
            Z_SIGNED : OUT STD_LOGIC_VECTOR((2 * N) - 1 DOWNTO 0)
        );
    END COMPONENT;

    COMPONENT ADDER_TREE IS
        GENERIC (
            NUM_INPUTS : INTEGER;
            DATA_WIDTH : INTEGER;
            SUM_WIDTH  : INTEGER
        );
        PORT (
            DATA_IN  : IN  STD_LOGIC_VECTOR((NUM_INPUTS * DATA_WIDTH) - 1 DOWNTO 0);
            DATA_OUT : OUT  STD_LOGIC_VECTOR(SUM_WIDTH - 1 DOWNTO 0)
        );
    END COMPONENT;

SIGNAL MULT : STD_LOGIC_VECTOR((ROW_A * COLUMN_B * COMMON * (SIZE_EACH_PRODUCT * 2)) - 1 DOWNTO 0);
CONSTANT SIZE_EACH_SUM : INTEGER := SUM_WIDTH((SIZE_EACH_PRODUCT * 2), COMMON);
BEGIN
    ROW: FOR I IN 0 TO ROW_A-1 GENERATE
        COL: FOR J IN 0 TO COLUMN_B-1 GENERATE
            NUM_PRODUCT: FOR K IN 0 TO COMMON-1 GENERATE
                U_MULTI: SIGNED_MULTIPLIER_WRAPPER 
                GENERIC MAP (N => SIZE_EACH_PRODUCT)
                    PORT MAP (
                    X_SIGNED => A((((I * COMMON) + K + 1) * SIZE_EACH_PRODUCT) - 1 DOWNTO (((I * COMMON) + K) * SIZE_EACH_PRODUCT)),
                    Y_SIGNED => B((((K * COLUMN_B) + J + 1) * SIZE_EACH_PRODUCT) - 1 DOWNTO (((K * COLUMN_B) + J) * SIZE_EACH_PRODUCT)),
                    Z_SIGNED => MULT(((((I * COLUMN_B * COMMON) + (J * COMMON) + K + 1) * (SIZE_EACH_PRODUCT * 2)) - 1) DOWNTO ((((I * COLUMN_B * COMMON) + (J * COMMON) + K) * (SIZE_EACH_PRODUCT * 2))))
                ); 
            END GENERATE NUM_PRODUCT;  

            U_TREE: ADDER_TREE
            GENERIC MAP (
                NUM_INPUTS => COMMON,
                DATA_WIDTH => SIZE_EACH_PRODUCT * 2,
                SUM_WIDTH  => SIZE_EACH_SUM
            )
            PORT MAP (
                DATA_IN  => MULT(((((I * COLUMN_B * COMMON) + (J * COMMON) + COMMON) * (SIZE_EACH_PRODUCT * 2)) - 1) DOWNTO ((((I * COLUMN_B * COMMON) + (J * COMMON)) * (SIZE_EACH_PRODUCT * 2)))),
                DATA_OUT => OUT_MULTIPLIER(((((I * COLUMN_B) + J + 1) * SIZE_EACH_SUM) - 1) DOWNTO ((((I * COLUMN_B) + J) * SIZE_EACH_SUM)))
            );
        END GENERATE COL;
    END GENERATE ROW;
END ARCHITECTURE STRUCTURAL;


