LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
PACKAGE MATRIX_TYPES IS
    TYPE MATRIX IS ARRAY (NATURAL RANGE <>) OF STD_LOGIC_VECTOR;
END PACKAGE MATRIX_TYPES;

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
PACKAGE ARRAY_PKG IS
    CONSTANT DATA_WIDTH : INTEGER := 16;--DATA WIDTH OF EACH ELEMENTS OF ARRAY
    TYPE COLUMN_ARRAY IS ARRAY (NATURAL RANGE <>) OF STD_LOGIC_VECTOR(DATA_WIDTH - 1 DOWNTO 0);

    TYPE MULT_ARRAY IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC_VECTOR;   
    TYPE SUM_ARRAY IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF SIGNED;
END PACKAGE ARRAY_PKG;

